This repository is another sketch of a movie database meant to showdown some Symfony's skills.

== Installation

1. Make sure the `8888` port is free on your host, and that you have docker obviously.
2. Then, execute the following commands in order:

    docker-compose up -d
    docker-compose exec application composer install
    docker-compose exec application yarn install
    docker-compose exec application yarn build

3. Copy the `.env.local.dist` to the same location as `.env.local`
4. Get an API Key from your https://www.themoviedb.org/settings/api[TMDB account] and set `TMDB_API_KEY` variable in `.env.local`

== What can be improved

- Add a debouncer on the search
- Add better feedbacks in front, and add small animation in general
- Find at least one movie that has videos attached to it
- Remove useless dependencies such as Doctrine, Mailer, etc.
- Cache the responses of the TMDB api. It makes no sense to make so many calls for almost nothing. Even a one-minute cache could reduce a lot the number of queries.
- Find a better library to handle routing and translation with VueJS
- Add test, testing is life.

== Mentions

- The front template used is from https://www.tailwindtoolbox.com/templates/multi-section-form[Tailwind Toolbox].
