services:
    # default configuration for services in *this* file
    _defaults:
        public: true
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Tests\Resources\:
        resource: '../tests/Resources'

    App\Tests\Resources\Spy\HttpClientSpy:
        decorates: 'Symfony\Contracts\HttpClient\HttpClientInterface'
